# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:5.6.30

pipelines:
  branches:
    master:
      - step:
          name: Deploy using SCP to PROD
          deployment: production
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: 'site_files/serving_database/'
                LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/*'
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: 'public_html/serving_database/css'
                LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/public/css/*'
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: 'public_html/serving_database/js'
                LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/public/js/*'
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: 'public_html/serving_database/images'
                LOCAL_PATH: '${BITBUCKET_CLONE_DIR}/public/images/*'